//@version=5
// Mean Reversion Strategy using Bollinger Bands. Long only. Trailing Stop.
strategy("BB Mean Reversion Long", overlay=true, default_qty_type=strategy.fixed, default_qty_value=2)

// BB Inputs
length = input(20, title="Bollinger Bands Length")
src = input(close, title="Source")
mult = input(2.0, title="Bollinger Bands Multiplier")

// Calculate Bollinger Bands
basis = ta.sma(src, length)
dev = mult * ta.stdev(src, length)
upper = basis + dev
lower = basis - dev

// Plot Bollinger Bands
plot(basis, color=color.blue, title="Basis")
p1 = plot(upper, color=color.red, title="Upper Band")
p2 = plot(lower, color=color.green, title="Lower Band")
fill(p1, p2, color=color.new(color.red, 90), title="Bollinger Bands Fill")

// Mean reversion strategy

// Entry
longCondition = ta.crossover(src, lower)
//shortCondition = ta.crossunder(src, upper)

if (longCondition)
    strategy.entry("Long", strategy.long, qty=2)

//if (shortCondition)
//    strategy.entry("Short", strategy.short)

// Exit Inputs
stopLossPerc = input.float(1.0, title="Stop Loss Percentage")
takeProfitPerc = input.float(2.0, title="Take Profit Percentage")
longStop = strategy.position_avg_price * (1-stopLossPerc / 100)
longTarget = strategy.position_avg_price * (1+takeProfitPerc / 100)
//debug
plot(strategy.position_size > 0 ? longTarget : na, color=color.green, style=plot.style_stepline, title="Long Target")
atrlength = input(14, title="ATR Length")
atrMult = input(1.0, title="ATR Multiplier for Trailing Stop")
longTrailRaw = close - ta.atr(atrlength) * atrMult
longTrail = math.max(longTrailRaw, longTarget)
//shortStop = strategy.position_avg_price * (1+stopLossPerc / 100)
//shortTarget = strategy.position_avg_price * (1-takeProfitPerc / 100)

if(strategy.position_size > 0)
    strategy.exit("Stop Loss", from_entry="Long", qty=2, stop=longStop)
if(strategy.position_size > 0 and close >= longTarget)
    strategy.exit("Take Profit", from_entry="Long", qty=1, limit=close)
    strategy.exit("Trailing Stop", from_entry="Long", qty=1, stop=longTrail)
//if(strategy.position_size < 0)
    //strategy.exit("Short Exit", from_entry="Short", stop=shortStop, limit=shortTarget)